### ISSUE TITLE
Add NFT contracts

### ISSUE THREAD

**Issue by hilalcomak** [uzh-eth-mp/app#34]

**Comment by dvdblk** [comment]
We already have the python code for some [erc721 events](https://github.com/uzh-eth-mp/app/blob/dev/src/data_collection/app/web3/transaction_events/erc721.py) 
https://github.com/uzh-eth-mp/app/blob/aa4f76d9a081e4faa26428fa89d0349c841d1df4/src/data_collection/app/web3/transaction_events/erc721.py#L17

and also support them in the [sql](https://github.com/uzh-eth-mp/app/blob/dev/src/db/sql/01-token-contract.sql)
https://github.com/uzh-eth-mp/app/blob/aa4f76d9a081e4faa26428fa89d0349c841d1df4/src/db/sql/01-token-contract.sql#L47

Closing this for now unless something more specific is required.
