### ISSUE TITLE
Add updated_at and created_at triggers to db

### ISSUE THREAD

**Issue by dvdblk** [uzh-eth-mp/app#74]

**Comment by dvdblk** [comment]
Should we add this for these four tables? @learn-want It's gonna be 2 columns but maybe `updated_at` is enough.

`timestamp` in postgresql is 8 bytes.

1. Block
* `2 * 8 B * 17 000 000` = 272 MB
* https://github.com/uzh-eth-mp/app/blob/32028f8313838963bcd63ad4a0761d1d030efbe0/src/db/sql/00-block-transaction.sql#L3
2. Transaction
* https://github.com/uzh-eth-mp/app/blob/32028f8313838963bcd63ad4a0761d1d030efbe0/src/db/sql/00-block-transaction.sql#L29
3. Internal transactions
* https://github.com/uzh-eth-mp/app/blob/32028f8313838963bcd63ad4a0761d1d030efbe0/src/db/sql/00-block-transaction.sql#L56
4. Transaction logs
* https://github.com/uzh-eth-mp/app/blob/32028f8313838963bcd63ad4a0761d1d030efbe0/src/db/sql/00-block-transaction.sql#L82

**Comment by learn-want** [comment]
I also think updated_at is enough, the update_at will be the created_time, then this column updates when adding new rows or re-collecting old rows  each time. Aslo, will the the timestap like the formart 2023/5/15, not like 158432434, right?

**Comment by dvdblk** [comment]
> updated_at is enough, the update_at will be the created_time

yes to both. The data basically never changes with our current set up. Each row is only inserted once, no further updates.

> then this column updates when adding new rows or re-collecting old rows each time

no. the timestamp column `updated_at` will only update when one of the values within this row is changed by any update query. Select queries don't change any values.

> Aslo, will the the timestap like the formart 2023/5/15, not like 158432434, right?
it will be of this format: 

```sql
db=# SELECT now();
             now              
------------------------------
 2023-05-15 19:42:33.42885+00
```

And you can query it like
```sql
db=# SELECT * FROM timestamp_demo;
         updated_at         
----------------------------
 2023-05-15 19:40:25.906722
 2023-05-15 19:40:30.673062
 2023-05-15 19:40:33.681263
(3 rows)

db=# SELECT * FROM timestamp_demo where updated_at >= '2023-05-15' AND updated_at < '2023-05-15 19:40:31';
         updated_at         
----------------------------
 2023-05-15 19:40:25.906722
 2023-05-15 19:40:30.673062
(2 rows)
```

**Comment by dvdblk** [comment]
> do you mean changing values? I think this should not happen, because these are the original data

Yes currently there is no code that changes any data in the tables (only insertions) and by the nature of blockchains the data shouldn't change anyway. But someone else might create an update statement that changes some rows and that will trigger the `updated_at` change to the current datetime.

**Comment by learn-want** [comment]
I see, this is a great mechanism!

**Comment by dvdblk** [comment]
done in #75
